### ISSUE TITLE
Assignment?

### ISSUE THREAD

**Issue by taylorbrooks** [taylorbrooks/rock_rms#8]
@jpowell Does this do what you'd expect?

https://github.com/taylorbrooks/rock_rms/blob/4553acb17347a67618b333081bbdc8adb382ad53/lib/rock_rms/responses/group.rb#L30-L36

https://github.com/taylorbrooks/rock_rms/blob/4553acb17347a67618b333081bbdc8adb382ad53/lib/rock_rms/responses/group_location.rb#L26-L28

**Comment by jpowell** [comment]
Yes. You will only get that information if you pass the correct `$expand` arguments in your `GET` query.

**Comment by taylorbrooks** [comment]
No, I've just never seen anyone do assignment like that.
